# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d02175e5175e7f28981fecf36f1a9f94a3e154c66d7b0b8d48d0a8dc1c0cb96c5d5bf36bd5831827c1c46bf89e7bef1ac78faf31d0ec5d06f8aa43c2d82da83

test:
  secret_key_base: f08f0b526dadc1bcd33a157c952db438aab02ccc6f1596d2bddafaa0c5784307df29871dcc6ea80b512a9ea042d2adde1f37200e72bee1fd0b2a9326747d0108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
